import "./css/style.css";
import "./css/header.css";
import "./css/hero.css";
import "./css/features.css";
import "./css/categories.css";
import "./css/products.css";
import "./css/deals.css";
import "./js/app.js";
import "./js/timer.js";
import "./js/menu.js";
import "./css/feature.css"
import "./css/footer.css"
import "./css/newsletter.css"
